### ISSUE TITLE
[secondary-sidebar] not wide enough for category names

### ISSUE THREAD

**Issue by pkra** [mathblogging/mathblogging.org#12]
Sciences&Humanities is too wide. That leads to overflow but the highlight-on-hover is fixed.

**Comment by pkra** [comment]
Not sure what the best approach is. I guess we should wait for the category names to settle.

**Comment by scoskey** [comment]
I guess we have to figure out the deal with fonts so we can be pretty sure if things fit

**Comment by pkra** [comment]
Yup. Maybe switch to flexbox after all...

**Comment by pkra** [comment]
Fixed by https://github.com/mathblogging/mathblogging.org/commit/c77d1e35be2301c125b31d6068ac99eb9f9dfcf8
