### ISSUE TITLE
SASS it up

### ISSUE THREAD

**Issue by pkra** [mathblogging/mathblogging.org#2]
Set up sass files correctly so jekyll builds out a single css file.

**Comment by pkra** [comment]
Hm....

Should we revert this? It adds a lot of unnecessary changes and makes my PR
invalid 😖

**Comment by scoskey** [comment]
I don’t know what PR is. The change seemed trivial enough to me, that’s why I did it.
Sam

**Comment by pkra** [comment]
Re-opening. 

I've reverted the commit that closed this (but it's saved in the branch scoskey-sass).

I've also modified my branch to copy your work (and extend it a little bit). Could you review #3?
